<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8871" started-at="2017-01-22T16:42:36Z" finished-at="2017-01-22T16:42:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8871" started-at="2017-01-22T16:42:36Z" finished-at="2017-01-22T16:42:45Z">
      <class name="tests.TestPages">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:tests.TestPages@3ffc5af1]" name="BeforeSuite" is-config="true" duration-ms="4223" started-at="2017-01-22T11:42:32Z" finished-at="2017-01-22T11:42:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="FAIL" signature="TestHomePage()[pri:0, instance:tests.TestPages@3ffc5af1]" name="TestHomePage" duration-ms="8842" started-at="2017-01-22T11:42:36Z" finished-at="2017-01-22T11:42:45Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at amazonPages.HomePage.SuccessMessage(HomePage.java:44)
	at tests.TestPages.TestHomePage(TestPages.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestHomePage -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:tests.TestPages@3ffc5af1]" name="AfterSuite" is-config="true" duration-ms="1738" started-at="2017-01-22T11:42:45Z" finished-at="2017-01-22T11:42:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- tests.TestPages -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
